### PR TITLE
Update IMDB dataset URL

### PR DESCRIPTION
**Pull request by dey4ss**

### CODE REVIEW

**Review by mweisgut — APPROVED** [review]
Why did the link change?

**Comment by dey4ss** [comment]
> Why did the link change?

Looks like Dropbox just wanted to irritate erveryone

**Review by julianmenzler — APPROVED** [review]
Just for reference: Is the file stored in the EPIC Dropbox account?

**Comment by dey4ss** [comment]
> Just for reference: Is the file stored in the EPIC Dropbox account?

Exactly

**Comment by mweisgut** [comment]
In the meantime, the link was already adjusted in #2458.

**Comment by Bouncner** [comment]
Oh, I did not expect #2458 to be merged before. Sorry.

**Comment by dey4ss** [comment]
No problem, the CI decided not to do a full run after queueing the job yesterday and I could not merge until the full run I started manually today was finished

**Pull request closed without merging**
