### PR TITLE
[WIP] Implement TPC-DS Benchmark

### PR DESCRIPTION
**Pull request by janetzki**
The table generator is currently file-based. We have to replace the file-based generator when hyrise-mp#3 is finished.

### CODE REVIEW

**Comment by janetzki** [comment]
@mweisgut I copied the PR from our former repo. Could you please take care of it now?

**Comment by mrks** [comment]
Please don't add # references to your own repo. #12 is an age-old Hyrise ticket, not one of yours.

**Comment by mrks** [comment]
[You can use a fully-qualified link](https://github.community/t5/How-to-use-Git-and-GitHub/In-a-commit-that-is-part-of-a-PR-from-outside-repository-xx/td-p/21719) (e.g., hyrise-mp/hyrise#12).

**Comment by mweisgut** [comment]
duplicate of #1679

**Pull request closed without merging**
