### PR TITLE
Fix SqliterRunner queries

### LINKED ISSUE #776: Mismatch between console and sqlite runner
This query works in the console, but not in the test runner: `CREATE VIEW count_view1 AS SELECT a, COUNT(DISTINCT b) FROM int_int_int GROUP BY a; SELECT * FROM count_view1;`

Console:
```
(debug)> load src/test/tables/int_int_int.tbl int_int_int
Loading src/test/tables/int_int_int.tbl into table "int_int_int" ...
(debug)> CREATE VIEW count_view1 AS SELECT a, COUNT(DISTINCT b) FROM int_int_int GROUP BY a; SELECT * FROM count_view1;
[PERF] operator[] used at src/lib/storage/value_column.cpp:37
	Performance can be affected. This warning is only shown once.

=== Columns
|       a|COUNT(DISTINCT b)|
|     int|             long|
=== Chunk 0 ===
|       9|                1|
|      10|                1|
|      11|                1|
===
3 rows total (COMPILE: 538 µs, EXECUTE: 457 µs (wall time))
```

Sqlite Runner:
```
[ RUN      ] SQLiteTestRunnerInstances/SQLiteTestRunner.CompareToSQLite/77
unknown file: Failure
C++ exception with description "Error while translating query plan:
  Error while compiling query plan:
  src/lib/sql/sql_translator.cpp:699 Couldn't resolve groupby column." thrown in the test body.
[  FAILED  ] SQLiteTestRunnerInstances/SQLiteTestRunner.CompareToSQLite/77, where GetParam() = "CREATE VIEW count_view1 AS SELECT a, COUNT(DISTINCT b) FROM int_int_int GROUP BY a; SELECT * FROM count_view1;" (28 ms)
[ RUN      ] SQLiteTestRunnerInstances/SQLiteTestRunner.CompareToSQLite/78
```

Right now, I am not quite sure where this comes from. Once this is fixed, we should be activate the view tests:

```
--- VIEWS disabled because of #367
--- CREATE VIEW count_view1 AS SELECT a, COUNT(DISTINCT b) FROM groupby_int_1gb_1agg_null GROUP BY a; SELECT * FROM count_view;
--- CREATE VIEW count_view2 AS SELECT a, COUNT(DISTINCT b) FROM groupby_int_1gb_1agg_null GROUP BY a; SELECT * FROM count_view WHERE a > 10;
--- CREATE VIEW count_view3 (foo, bar) AS SELECT a, COUNT(DISTINCT b) FROM groupby_int_1gb_1agg_null GROUP BY a; SELECT * FROM count_view WHERE a > 10;
+-- VIEWS
+CREATE VIEW count_view1 AS SELECT a, COUNT(DISTINCT b) FROM int_int_int GROUP BY a; SELECT * FROM count_view1;
+CREATE VIEW count_view2 AS SELECT a, COUNT(DISTINCT b) FROM int_int_int GROUP BY a; SELECT * FROM count_view2 WHERE a > 10;
+CREATE VIEW count_view3 (foo, bar) AS SELECT a, COUNT(DISTINCT b) FROM int_int_int GROUP BY a; SELECT * FROM count_view3 WHERE a > 10;
```

### PR DESCRIPTION
**Pull request by lawben**
Fixes #776.

### CODE REVIEW

**Comment by mrks** [comment]
Thank you for looking into this and finding the cause. I feel in order to actually fix the problem we have to either rename the columns in the file (my preferred solution) or rename the table. When I see `int_int_int`, I expect it to come from `int_int_int.tbl`, not `int_int_int_100.tbl`, which has different column names.

**Comment by lanice** [comment]
The only tables that are used in the sqlite testrunner are in the tables/sqlite subfolder. I have no problem with renaming the columns from `int_a` etc to `a` etc though. The table schema from `int_int_int.tbl` and `int_int_int_100.tbl` would still differ in the way that `int_int_int_100.tbl` has the additional `id` column.

**Comment by mrks** [comment]
Then maybe `int_int_int_100.tbl` should simply get a different name as a file and in the tests. I would (1) expect a `SELECT * FROM foo` to refer to a file `foo.tbl`, not to `foo_100.tbl` and (2) for `foo.tbl` and `foo_100.tbl` to have the same column layout.

**Comment by lanice** [comment]
I don't really agree with (1)*, but if that's the way to go how about `id_int_int_int_100.tbl`, and `id_int_int_int_100` in the tests?

* for example in the tests I picked one single tpch table for testing, `src/test/tables/tpch/sf-0.001/customer.tbl`, and named it `tpch_customer`, so that in the test file you can see that this is the tpch customer table. And if you really need to see the file where this is coming from, well then you can just take a look in the `sqlite_testrunner.tables` file where the imports are specified. Because there is no single `customer.tbl` file which you could relate to, we have the `.../sf-0.001/customer.tbl`  and the `.../minimal/customer.tbl` file.

I agree with (2).

**Comment by mrks** [comment]
Maybe I overgeneralized my statement in (1). The TPC-H eample makes perfect sense. It is just that in this case, expecting `int_int_int == int_int_int.tbl` seems to be reasonable. Your suggestion works for me.

**Comment by lawben** [comment]
@lanice do you want to take care of those changes?

**Comment by lanice** [comment]
Sure

**Comment by lanice** [comment]
Renamed the file (`int_int_int_100.tbl` -> `id_int_int_int_100.tbl`) and the columns within the file (removed the `int_` part), and adjusted the tests.

**Comment by mrks** [comment]
Thanks!

**Pull request merged**
