### PR TITLE
Disable USDT in TSan builds

### PR DESCRIPTION
**Pull request by mrks**

### CODE REVIEW

**Comment by Bensk1** [comment]
Apparently, that did not fix it yet:

- https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/master/471/pipeline/
- https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/organizations/jenkins/Hyrise%2Fhyrise/detail/try_ninja_build/3/pipeline/71

**Comment by mrks** [comment]
Could you add a debug print to make sure that the macro actually excludes the probes?

**Comment by Bensk1** [comment]
It seems like the `#ifndef __SANITIZE_THREAD__` is only used on apple platforms because it is guarded by `#if defined(__APPLE__) || defined(__MACOS__)`. The same applies for `#include "provider.hpp"` that's why I don't understand how it does work at all.

**Comment by mrks** [comment]
Argh, right. I now seem to remember that systemtap brings its own `DTRACE_PROBEn` macros. Use the same file to `#undef DTRACE_PROBEn` on non-OS X?

**Pull request merged**
