### PR TITLE
Support JOIN ... ON ... AND ...

### PR DESCRIPTION
**Pull request by mrks**

### CODE REVIEW

**Comment by mrks** [comment]
This still fails:

```
script src/test/tables/tpch/load.script
SELECT c_custkey, count(o_orderkey) FROM customer left join orders on c_custkey = o_custkey WHERE o_comment = 'bla' GROUP BY c_custkey;
```

**Comment by mrks** [comment]
Thinking about it some more, the approach that I chose here only works for inner joins. I don't have a good idea on how to do it for outer joins, but it probably has to be in the operators themselves. :/

**Comment by TwoLaid** [comment]
I was  just about to mention that this only works for inner joins, too. Also, this approach seemed very inflexible, because it only supports one `AND`, not things like `ON .. AND .. AND .. AND ..`.

I'm sure we can find a better solution (:

**Comment by mrks** [comment]
I am pretty sure that it would have worked with multiple ands as well, but have not tested it. That is because in that case, the `and_predicate` would have been another kOpAnd node.

**Comment by TwoLaid** [comment]
aah yes, you're right. sorry

**Pull request closed without merging**
