### PR TITLE
Remove JitBaseSegmentIterator

### PR DESCRIPTION
**Pull request by mrzzzrm**
Code smell, imo, to have a special base class of a core class, dedicated to a particular component. Thankfully it wasn't used.

### CODE REVIEW

**Comment by mrks** [comment]
Mmh? Did you just re-add everything?

**Comment by mrzzzrm** [comment]
If you need to access iterators polymorphically you can always wrap them - which I think is what the JIT does anyway now (cf. `JitSegmentReader`)

**Comment by cmfcmf** [comment]
Ahh, I was wondering whether I was missing some sort of voodoo C++ JIT magic, because I couldn't find any usages of the `JitBaseSegmentIterator` when debugging segment iterators for #1531. Good to know it wasn't used :+1:

**Comment by mrzzzrm** [comment]
> Ahh, I was wondering whether I was missing some sort of voodoo C++ JIT magic, because I couldn't find any usages of the JitBaseSegmentIterator when debugging segment iterators for #1531. Good to know it wasn't used

If in doubt, always ask - Issues are one option, PMs another!

**Pull request merged**
