### PR TITLE
Mp18/radix bits

### LINKED ISSUE #897: Hash Join does not work for _radix_bits=1
@Bouncner am I missing something?

### PR DESCRIPTION
**Pull request by marcelja**
Fixes #897. The problem was that different types were hashed. It worked for larger numbers of radix bits because each partition only had the same values.

Is it ok to add a default constructor argument for the number of radix bits?

### CODE REVIEW

**Comment by Bouncner** [comment]
One of the mail goals of the radix partitioning is to create hash tables that are cache resident in the probing phase.
So I'd vote for something that looks at the length of the table to be hashed. Then the radix bits should be chosen in a way that we might end up with a hash table at half the L2 cache size for each partition (half the size because there will always be some form of skew).
So the pure data itself might be around a quarter of the L2 size (hash table size is around a factor 2x of the actual data).

@mrks : any idea what a "fair assumption" for L2 sizes is? Does that make sense what I just said?

**Comment by mrks** [comment]
I'm not sure if a quarter is a good measure. For L2 size, I would take 256k.

**Comment by Bouncner** [comment]
So our hash tables (cuckoo) work best at a fill level around 0.45. Thus doubling.
You think the other factor 2x for skew is too much/too little?

**Comment by mrks** [comment]
I have no idea. Might be better to experiment with that.

**Pull request merged**
