### PR TITLE
Fix boost_default_memory_resource alignment

### PR DESCRIPTION
**Pull request by mrks**
testing, WIP

### CODE REVIEW

**Comment by mrks** [comment]
Looks good. We'll see if this fixes the CI builds across all branches, but it is something that should be done in any case.

**Comment by Bensk1** [comment]
Hm, malloc/free should be defined in `stdlib.h`. But `memalign` is in malloc.h which does not exist (at least not where we are looking for it). Apparently, there is `posix_memalign` in `stdlib.h` or `std::aligned_alloc` in `cstdlib` if that helps.

**Comment by mrks** [comment]
Haha. In the art of computer science, subtractive methods are generally underestimated.

**Comment by mrks** [comment]
While it is no longer necessary to ship the default resource ourselves, boost simply continues to ignore that parameter:

https://github.com/boostorg/container/blob/f73fb1442a0d714e97506b6fa86f5a1f16da7ddc/src/global_resource.cpp#L34

**Comment by mrks** [comment]
Ok, as memcheck doesn't seem to like me and as the ignored alignment is equally used in boost, I'll close this.

**Pull request closed without merging**
