### PR TITLE
Don't run NUMA placement if we only have one node

### LINKED ISSUE #562: Division by zero in inverted_entropy()
In `migration_preparation_task.cpp`: if there is just one NUMA node, `max_entropy` will be zero, leading to division by zero when doing `return (max_entropy - entropy) / max_entropy;`

### PR DESCRIPTION
**Pull request by mrks**
fixes #562

### CODE REVIEW

**Comment by mrks** [comment]
I am not trying to take a shortcut. If we only have one node, that tasks should not run at all. Stopping it as early as possible makes sense to me.

Do you have a reason why we should let the program get to the point where it calculates the entropy? If so, we can choose that path as well.

**Comment by mrzzzrm** [comment]
The Assert was wrong imo, checking for more than 0 nodes instead of more than 1. Otherwise okay, lets ship.

**Comment by mrzzzrm** [comment]
(I tend to move asserts close to the point where the condition they are checking is actually required, but that's a matter of taste, especially in this case, I guess.)

**Comment by mrks** [comment]
D'oh. Counting is hard. Thanks for catching that.

**Comment by Bouncner** [comment]
Allow me a (as usual) stupid question: does this break when we remove NUMA nodes at runtime and reach nodes=1?

**Comment by mrks** [comment]
As of now, we cannot remove NUMA nodes anyway. The topology is determined at startup. When would we want to do that?

**Comment by Bouncner** [comment]
Was just a question out of interest and something that might later make problems, if we hardcode some parts.

I have no idea if or when this will ever be the case. :)
What brought me to that idea what actually your proposal with heterogenous systems, where you might decide at one point that a NUMA node can be shut down for quite some time to reserve energy.

**Pull request merged**
