### PR TITLE
RuleBatches

### PR DESCRIPTION
**Pull request by mrzzzrm**
A RuleBatch can either be iterative, i.e. it executes the Rules until they stop changing the LQP, or execute their rules just once.

Details (per-batch `max_num_iterations`, batch names...) might be tweaked once actual batches arrive, but this should provide the template for those who wish to work with rule batches

### CODE REVIEW

**Comment by mrzzzrm** [comment]
You mean the order in which the batches are applied? That's a good idea.

**Comment by Bensk1** [comment]
Exactly

**Comment by mrzzzrm** [comment]
Hope this makes it clear.

**Comment by Bensk1** [comment]
Perfect

**Pull request merged**
