### PR TITLE
Rename misnamed BaseCompressedVector and Corresponding Files and maybe more

### PR DESCRIPTION
**Pull request by tjjordan**

### CODE REVIEW

**Comment by dey4ss** [comment]
This is all about `BaseCompressedVector` &rarr; `AbstractCompressedVector` (and corresponding `*Decompressor`), right? Maybe use a more specific PR name.

**Review by dey4ss — APPROVED** [review]
Pedantic, but you *rename* the classes rather than *refactoring* their implementations. LGTM. However, I think it's fair to merge #2402 first.

**Comment by dey4ss** [comment]
Just came across `BaseSegmentEncoder`/`SegmentEncoder` (see `storage/base_segment_encoder.hpp`). Would this class fit into this PR as well?

**Comment by tjjordan** [comment]
Good catch!
But `BaseSegmentEncoder` is only an non-templated interface for `SegmentEncoder`, so Base should be the correct prefix.

**Comment by dey4ss** [comment]
Maybe we should discuss our definitions of `Base*`/`Abstract*` in a fortnightly. Currently we have:
 | Name      | Meaning                                                                                                                                                                                                                                                |
| --------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Abstract* | An incomplete class used for *dynamic* polymorphism (i.e., OOP with run-time resolved virtual methods). It has pure virtual methods that need to be implemented by subclasses.                                                                         |
| Base*     | An incomplete class used for *static* polymorphism (i.e., compile-time resolved templates). It implements methods shared by all implementations. Mostly, it is used so that we have a non-templated superclass, which can be stored in, e.g., a vector. |

`BaseSegmentencoder`: &#x2611; static polymorphism, &#x2612; methods shared by implementations.

**Comment by mweisgut** [comment]
Let's discuss this soon again, @Bouncner @tjjordan @dey4ss @benrobby @mweisgut.

**Comment by mweisgut** [comment]
> Maybe we should discuss our definitions of `Base*`/`Abstract*` in a fortnightly. Currently we have:
> 
> Name	Meaning
> Abstract*	An incomplete class used for _dynamic_ polymorphism (i.e., OOP with run-time resolved virtual methods). It has pure virtual methods that need to be implemented by subclasses.
> Base*	An incomplete class used for _static_ polymorphism (i.e., compile-time resolved templates). It implements methods shared by all implementations. Mostly, it is used so that we have a non-templated superclass, which can be stored in, e.g., a vector.
> `BaseSegmentencoder`: ☑ non-templated, ☒ methods shared by implementations.

I suggest moving the discussion to a new issue and renaming `BaseCompressedVector` with this PR.

**Comment by mweisgut** [comment]
Closing it for now. Feel free to reopen if it becomes a priority.

**Pull request closed without merging**
