### PR TITLE
Update compact_vector library and use a non-system library again

### PR DESCRIPTION
**Pull request by Bouncner**
This PR updates the `compact_vector` third party library to get rid of some deprecation errors with LLVM 13 (see https://github.com/gmarcais/compact_vector/issues/6). Due to these errors, #2458 set `compact_vector` to be a system library. This is no longer required now.

### CODE REVIEW

**Comment by dey4ss** [comment]
Any idea why CI's clang does not find the STL `<compare>` header`

**Comment by Bouncner** [comment]
Interesting, I have no idea though.

I though both clang versions would use the same `libstdc++`.

**Comment by Bouncner** [comment]
I'll bother you again once this PR get through the CI pipeline.

**Comment by Bouncner** [comment]
I'll try it again later.

**Comment by Bouncner** [comment]
Let's see if something happened.

**Comment by Bouncner** [comment]
Already fixed by #2402.

**Pull request closed without merging**
