### PR TITLE
Resolve null ptr issue in specialised operator code with LLVM6 (#911)

### LINKED ISSUE #911: JIT with LLVM6 causes null ptr exception after specialisation
`SELECT column+column FROM table;` causes a runtime null ptr exception when JIT with LLVM6 is used and query is specialised.
Works with LLVM5.

[Solution found, bug created to properly address it in PR]

### PR DESCRIPTION
**Pull request by FabianWiebe**
Removed null ptr issue in LLVM6 during execution of specialised jit code by clearing a `runtime_value_map` after inlining of each function.
The map caches the retrieved runtime values during function inlining. This lead to a problem when a function was inlined multiple times with different objects. The programme execution path depends on the context objects as they determine which path is taken at a condition or switch statement. Inlining and specialising a function with the wrong information can, therefore, cause as in our case the dereferenciation of null pointers.

The specialisation test case takes on my MacBook 276ms. I hope that is still acceptable as it is the only time that a query is actually specialised in the test cases.

Closes #911 .

### CODE REVIEW

**Comment by FabianWiebe** [comment]
@mrks Yes, I think so.

**Comment by mrks** [comment]
This one comes to mind: https://github.com/hyrise/hyrise/commit/086c943b222f70c134d588e8b937a35854850555

**Comment by FabianWiebe** [comment]
Yes,  the undefined behavior sanitizer in the referenced commit has been reenabled with this pr. There exist currently two exceptions in the jittable code to prevent false positives, which I just rechecked and believe to be valid:
* One to allow checking whether a jit address pointer is a valid. Obviously, the sanitizer does not like accessing an invalid address during the check.
* The second is to get the class type of a virtual function call by casting the pointer to an empty non-parent virtual class. I am still in the process of understanding this part of the code.

**Comment by mrks** [comment]
There was a discussion about the second one in the PR that introduced it. IIRC, it works, but is simply illegal. If we can find a different solution for that, I would prefer that.

**Pull request merged**
