### PR TITLE
Add missing forward declaration

### PR DESCRIPTION
**Pull request by Bouncner**
Same as with #2042. If people continue to disable PCH (I know I am not the only one), we might want to automatically check for building without it.

### CODE REVIEW

**Comment by Bensk1** [comment]
I can imagine that this is really annoying

**Comment by mrks** [comment]
Feel free to add a non PCH build (similar to the ODR one)

**Comment by Bouncner** [comment]
I’ve never touched this Jenkins mess until now. Anybody here who wants?

**Comment by Bensk1** [comment]
I can do it later

**Comment by Bouncner** [comment]
Interestingly, @Boffmann observe the same issue even without disabling PCH.

**Comment by mrks** [comment]
Have a try if `-DCMAKE_DISABLE_PRECOMPILE_HEADERS=On` is sufficient: https://cmake.org/cmake/help/git-stage/variable/CMAKE_DISABLE_PRECOMPILE_HEADERS.html#variable:CMAKE_DISABLE_PRECOMPILE_HEADERS

**Comment by Bouncner** [comment]
`-DCMAKE_DISABLE_PRECOMPILE_HEADERS=On` is sufficient to trigger the `Table not defined` issue. So that would apparently work.

@Bensk1 : would you want that in another PR or in here?

**Pull request merged**
