### PR TITLE
StorageManager: Add add_or_replace_table, fixes #1187

### LINKED ISSUE #1187: Console does not like TPC-H data being generated twice
We should overwrite the tables, not crash.

### PR DESCRIPTION
**Pull request by mrks**

### CODE REVIEW

**Comment by mrks** [comment]
> It's minor I know, but I dislike this for several reasons. You try to fix the specific case of running gentpch twice in the console - why not fix it in the console itself, e.g. by removing all TPCH-named tables before triggering the generator and being verbose about it?

That's what I started before I realized that the same needs to be done for TPC-C and the console does not know about the names for either.

> The StorageManager has the same set of functions for views and tables, now there is inconsistency.

Happy to add that for views.

> There should be one go-to way to add tables to the SM, I can already see unwitting devs using add_or_replace all over the place because they do not want to do proper error handling

You have a point there. My goal was to avoid repeating the `if (has_table) drop_table(); add_table();` all over the place. If you think that code duplication in the console would be better, I'll be happy to do it that way.

> As a console-user, what if a had a nation table from another source and didn't know TPCH contains one as well? It would get replaced without me noticing.

`¯\_(ツ)_/¯`. Unless we want to bloat the console code with asking for confirmation, that's what you get. Personally, I find the use case of wanting to check things with a different scale factor more relevant.

**Comment by mrzzzrm** [comment]
I'll leave it to you. Personally I'd prefer a `add_or_replace_table` in the console. This function would then print a line whenever it replaces a table.

**Comment by lanice** [comment]
I definitely agree that we want this feature, to quickly re-generate the tables with a different scale factor in the console :+1: 
Either way I think we should add a warning or message if a table gets replaced.
I'm slightly more in favor of having the option in the StorageManager. The `unwitting devs` you mention still have to go through code reviews, where one can question if that is the necessary call, or if using `add_table` is sufficient.

**Comment by mrks** [comment]
If we want a warning, we won't get around doing it in the console. And if we have to check if the table exists, calling drop_table is not far. Let's do it that way then.

**Pull request closed without merging**
