### PR TITLE
Enable table data loading from directory in server.cpp

### PR DESCRIPTION
**Pull request by Bouncner**
This PR enables loading data from a directory. Initially, my goal was to enable creating the data for JOB data, but JOB only uses the `FileBasedTableGenerator` anyways.

This way one can easily import data from "any" directory *and* gains the advantage of automatically loading binary data when possible.

### CODE REVIEW

**Comment by mrks** [comment]
Any reasons you don't use the import commands?

**Comment by Bouncner** [comment]
Mainly convenience for working on the JOB (not having twenty queries to load and also not checking if a binary is loadable or not).

If that convenience is considered "not worth it", I don't mind to close this PR.

**Comment by mrks** [comment]
One could easily put this into a script rather than the server binary. Personally, I feel like this isn't the job of the server and the TPC-H convenience commands should not be taken as precedent.

**Comment by mrks** [comment]
We could put a `load_join_order_benchmark.sql` into the resources folder for convenience though.

**Comment by Bouncner** [comment]
Forgot to mention another factor that is pretty significant: load time. When using the `FileBasedTableGenerator`, we get the parallelization of encoding and histogram generation of the `AbstractTableGenerator`. That's a huge difference (mostly for TPC-H).
I haven't tested what happens if I add tables in parallel though, but I remember that it was likely to crash when tables are added in parallel to the storage manager.

**Comment by mrks** [comment]
Sounds like something we should fix in general though, not just by adding convenience methods to the server though. :/

**Comment by Bouncner** [comment]
Yeah, absolutely. This was just a note to have this issue written down. Not meant to reopen this PR.

**Pull request closed without merging**
