### PR TITLE
Use bigger tables for SQLiteTestRunner

### PR DESCRIPTION
**Pull request by lanice**
#460 

Found a few problems during this, which I already noted in separate issues.
Furthermore, the execution of the testrunner test takes quite long now (~28 seconds on my machine). The only option here would be on cutting down on the tables even more, and e.g. don't use the TPC-H tables at all, and try to fit every query in the context of the remaining tables.

Also: I didn't delete any of the small tables for now, I was not sure where and for what else they might be used.

### CODE REVIEW

**Comment by lanice** [comment]
Another option would be to not re-load the tables for every query. This limits us to only test non-manipulating queries here.

**Comment by mrks** [comment]
Would it be possible without much work to run this on small tables in the regular test suite and on a bigger set in the system test that is executed by the CI?

**Comment by mrks** [comment]
But reusing tables is fine for me as well. If you have a modifying table, you simply have to load your own table.

**Comment by lanice** [comment]
I don't really like the first option, running the tests on different tables on the own system compare to the CI. It's probably possible though, my first thought would be to add another target for that and then run different test targets.

What I have done now is actually removed three of the four TPC-H tables that I used for the tests, since they where used only in I think 3 or 4 queries anyway. I have rewritten the queries that they also only use the generated 100-row tables and the one TPC-H customer table. With that execution is a lot faster again, about 8.9 seconds on my machine.

**Pull request merged**
