### PR TITLE
Rename SelectExpression to SubqueryExpression

### PR DESCRIPTION
**Pull request by mrzzzrm**
Ages ago @Bouncner pointed out that "SelectExpression" is not really a good name, since "Select" is a word that has meaning in SQL, but our LQP/PQPs should be ignorant about SQL.

So I finally renamed it them to "SubQueryExpressions", is that better?

Feel free to reject if this makes code in the making mergehell....

### CODE REVIEW

**Comment by mrks** [comment]
Let's discuss this on Wednesday.

**Comment by Bouncner** [comment]
We stumpled about this issue again with my DYOB group. Sub(q/Q)uery sounds much better for me. At least now I understand its usage in the log. plans I have written so far.
But: I don’t dare to comment on the general term since I don’t know about all its usages. Also: I am not fluent enough in all the relation/logical terms to know whether we might mix up things here (logical vs. SQL world)...

But you guys will surely solve that on Wednesday. :-)
I will pass due to vacation this week.

**Comment by mrzzzrm** [comment]
Rename to SubqueryExpression

**Comment by mrzzzrm** [comment]
Its LQPSubqueryExpression and PQPSubqueryExpression now.

**Pull request merged**
