### PR TITLE
Fix ColumnPruningRule parameter naming

### PR DESCRIPTION
**Pull request by mrzzzrm**

### CODE REVIEW

**Comment by mrzzzrm** [comment]
Wait, you already fixed that and Jenkins reported anyway or something

**Comment by mrks** [comment]
Hmm? I didn't do anything iirc.

**Comment by mrzzzrm** [comment]
image
Here both names were "node" before

**Comment by mrzzzrm** [comment]
image
But going to the code, it's named "root" in the cpp.

**Comment by mrks** [comment]
I can't follow. I don't think I ever touched that file. The master is failing because you are violating the clang-tidy rules. When the PR that brought in that rule was built, FullCI did not yet require clang-tidy to pass

**Comment by mrzzzrm** [comment]
Forget all that, sorry, I mixed up ChunkPruningRule and ColumnPruningRule - they look sooo similar, though

**Pull request merged**
