### PR TITLE
Rename install.sh

### LINKED ISSUE #1922: Change install.sh to install_dependencies.sh?
"Install" sounds like we would install Hyrise somewhere, which people might not want.

### PR DESCRIPTION
**Pull request by mrks**
TODO:

- [x] Update Readme
- [ ] Update Wiki
- [ ] Update DYOD slides

I suggest that this fixes #1922, let's continue the discussion over there, if necessary.

### CODE REVIEW

**Comment by Bouncner** [comment]
I guess you grepped all files for occurrences of install.sh?

**Comment by Bouncner** [comment]
The changes look good to me. Should we wait for a final go when the wiki and the slides are updated?

**Comment by mrks** [comment]
Sure. Let's give people a day or two to comment on this.

**Comment by Bouncner** [comment]
https://github.com/hyrise/hyrise/blob/master/README.md
https://github.com/hyrise/hyrise/wiki/Docker-Image
https://github.com/hyrise/hyrise/wiki/Step-by-Step-Guide
https://github.com/hyrise/hyrise/wiki/Installation
Upcoming fork of: https://github.com/hyrise/DYOD_WS1920

**Comment by mrks** [comment]
Hmpf. Forgot to address this in the fortnightly.

**Comment by Bensk1** [comment]
#1922 is reasonable and this PR is an elegant solution.

**Comment by mrks** [comment]
Thanks for the list, @Bouncner.

**Pull request merged**
