### PR TITLE
Skip SchedulerTest.VerifyTaskQueueSetup on low core count

### PR DESCRIPTION
**Pull request by cmfcmf**
As discussed in https://github.com/hyrise/hyrise/pull/1342 and https://github.com/hyrise/hyrise/pull/1339.

### CODE REVIEW

**Comment by Bouncner** [comment]
Looks good to me. But where does that magic 4 come from? Doesn't it make sense to run it with 2 workers as well?

**Comment by Bouncner** [comment]
Ah ok. Could you add a ahort comment to the skipping part?

**Comment by cmfcmf** [comment]
@Bouncner done in https://github.com/hyrise/hyrise/pull/1353/commits/c4a5af30a0e8758d2e99197008ef5b61c6aed5ef.

**Comment by mrks** [comment]
Did you already accept the invitation to the Hyrise team?

**Comment by cmfcmf** [comment]
> Did you already accept the invitation to the Hyrise team?

Yes, I did.

**Comment by mrks** [comment]
It's working now. I didn't add the team to the repo.

**Pull request merged**
