### PR TITLE
Avoid coverage badge caching and change info text

### PR DESCRIPTION
**Pull request by Bouncner**
This tiny PR does two things:
 - change a text during benchmark loading
 - adds contributors

**Badge**:
The coverage badge URL remains the same (Jenkin's badget) but we internally rewrite the header caching information with the HPI to ensure that badges are not cached. This has been the reason for the previous solution on heroku.

**Benchmark information**:
Change the text for table encoding and stats generation from `Encoding 'lineitem' - no encoding necessary (12 s 248 ms)` to `Processing 'lineitem' - no encoding necessary (12 s 248 ms)`. Since there are stats generated, I am always curious what a lot cores can do for 12 seconds, when no re-encoding is necessary.

### CODE REVIEW

**Comment by dey4ss** [comment]
Is there any chance we can host this under an hpi address? So it would be independent of any of us personally

**Comment by Bouncner** [comment]
> Is there any chance we can host this under an hpi address? So it would be independent of any of us personally

This is rather a quick fix for now. But honestly, I don't see a good change running it within the HPI. I haven't found a way to instrument Jenkins to provide the correct headers and running a service within the HPI that is accessible from the outside has always been quite a pain.

I'll ask Matthias if things are different now.

**Comment by Bouncner** [comment]
We might have found a better solution. Will reopen later.

**Comment by Bouncner** [comment]
We found a way to overwrite Jenkin's header information which is also picked up by Github. Thus, badges are no longer cached.

Reopening this PR for this little info text change and to to add missing contributors of Hyrise. The students contributed #2396 as part of the DYOD seminar but missed to add themselves to the contributors list.

**Review by dey4ss — APPROVED** [review]
Sure Markus will find the time to review these serious and comprehensive changes?

**Comment by Bouncner** [comment]
He will regret it if he doesn't find the time!

No, I already told him that I did mausgerutscht.

**Pull request merged**
