### PR TITLE
Implement sorted column store merge

### PR DESCRIPTION
**Pull request by Bensk1**
This implements mainly the sorted column store merge. It includes as well some code beautification and performance optimisation.

### CODE REVIEW

**Comment by martinfaust** [comment]
@Bensk1 : Could you please add a 4 column testcase (ABCD), where the sort order is defined by B-C-A?

**Comment by Bensk1** [comment]
@martinfaust is https://github.com/Bensk1/hyrise/commit/04e388faf5c2a52d74cbd2bbe90a1d602b024521 fine for you?

**Comment by martinfaust** [comment]
@Bensk1  Nope. Can you build data that stresses the cascaded sort even more, e.g. Where the sorted results would be

3,4,5
4,4,5
3,5,5

if sorted by BCA?

Is
+  cid.addField(1);
+  cid.addField(2);
+  cid.addField(0);
the one and only thing that defines the sort order for the main?

**Comment by Bensk1** [comment]
@martinfaust Should be done.

**Comment by martinfaust** [comment]
@Bensk1  Thanks! Can you please squash your commits?

**Pull request merged**
