### PR TITLE
Fix SHOW COLUMNS

### LINKED ISSUE #1137: show tables is broken
```
Hyrise is running a (debug) build.

(debug)> show tables;
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: src/lib/logical_query_plan/abstract_lqp_node.cpp:180 Can only forward input expressions, if there is only a left input
```

Also, apparently untested.

### PR DESCRIPTION
**Pull request by mrzzzrm**
Fixes #1137

Tests preventing this type of bug will either come with the console tests or if we ever implement SQL to Table tests again.

### CODE REVIEW

**Comment by mrks** [comment]
Why do we need SQL-to-Table tests for this? Can't we test this like any other SQL-to-LQP translation?

**Comment by mrzzzrm** [comment]
Ah yeah, good point, will add that.

**Comment by mrzzzrm** [comment]
(Currently there are no SQL end to end tests for our non-query operations so we cannot be sure the optimizer doesn't break them, but your suggestion will fix this particular case)

**Comment by mrzzzrm** [comment]
done

**Pull request merged**
