### PR TITLE
Fix unterminated string in server test, update googletest

### LINKED ISSUE #755: Detecting incorrect STL usage
Just dumping this here, should be trivial to enable for CI

https://kristerw.blogspot.de/2018/03/detecting-incorrect-c-stl-usage.html

### LINKED ISSUE #920: Find out why the sanitizer lies to us
Issue in [line 275](https://github.com/hyrise/hyrise/blob/f76bc39ac5dc0ac804da8cb8f7ba15246abed89c/src/lib/operators/union_positions.cpp) `if (column_id == _column_segment_offsets[next_segment_id]) {`
At some point `next_segment_id` is `1` and `_column_segment_offsets` has a size of `1`.
To show issue on [Jenkins](https://ares.epic.hpi.uni-potsdam.de/jenkins/blue/rest/organizations/jenkins/pipelines/Hyrise/pipelines/hyrise/branches/fabian%252Ftest_jenkins_sanitizer/runs/2/nodes/62/steps/114/log/?start=0), I added a function `at`: `_column_segment_offsets.at(next_segment_id)` to enable bounds checking.

Found via locally running sanitizer tests. Somehow, Jenkins sanitizer does not find them.

Found via running following tests:
* UnionPositionsTest:SelfUnionOverlappingRangesMultipleColumns
* UnionPositionsTest:MultipleReferencedTables
* SQLPipelineStatementTest:PreparedStatementMultiPlaceholderExecute
* SQLPipelineStatementTest:MultiplePreparedStatementsExecute

### PR DESCRIPTION
**Pull request by mrks**
closes #920 

Right now, this fails in the server component. @lawben - could you please have a look?

### CODE REVIEW

**Comment by mrks** [comment]
@lawben ping?

**Comment by lawben** [comment]
oh, i just noted I never sent my last comment here :/ 
so i spent some time on it last week and have no idea what is causing this. debugging is kinda hard. I can have a look into this again tomorrow with some different approaches

**Comment by mrks** [comment]
Argh. This is an ABI mismatch between the system's boost version not using _GLIBCXX_DEBUG and us using it. The only solution to this would be to build our own boost version and link against that. Even though we would only have to do that on the CI server, I don't like that idea.

See https://svn.boost.org/trac10/ticket/7666

Let's try and get #722 instead?

Still, we should at least get the two minor fixes in. Updating googletest doesn't sound like a bad idea either.

**Comment by mrks** [comment]
FYI: Found it by attaching gdb in the docker image.

```
Thread 65 "hyriseTest" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffde394f700 (LWP 3921)]
0x00007ffff76b47e8 in boost::detail::thread_data_base::~thread_data_base() () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1
```

Searching for "thread_data_base segfault" gives a good start.

**Comment by lawben** [comment]
How come this now passes in CI? Did you change boost? I'm a bit confused to where the problem is right now

**Comment by mrks** [comment]
I removed the glibc debug things (I.e., the original core of this PR).

This is now only three trivial things as you can see in the diff

**Pull request merged**
