### PR TITLE
Enable TSan for NUMA builds

### LINKED ISSUE #1006: Enable TSAN for NUMA builds
Currently, TSAN reports a bunch of possible data races for the `PausableLoopThread` and the `MigrationPreparationTask`. As soon as the numa support has been reworked, we should activate thread sanitisation checks for numa builds.

### PR DESCRIPTION
**Pull request by mrks**
fixes #1006 as the problematic `MigrationPreparationTask` is long gone. If `PausableLoopThread` still causes issues, those need to be addressed, as it is used in #1493.

### CODE REVIEW

**Comment by mrks** [comment]
Hoping to get the issue list down to 80 this weekend. ;)

**Comment by mrks** [comment]
Shame. As soon as I have to change more than one thing and there is no compiler whining, I fail. :(

**Comment by mrzzzrm** [comment]
was just about to throw my torch ;)

**Comment by mrzzzrm** [comment]
> Hoping to get the issue list down to 80 this weekend. ;)

Merging #1550 would make us CRUSH that mark.

**Pull request merged**
