### PR TITLE
Add Cache Meta Tables

### PR DESCRIPTION
**Pull request by dey4ss**

### CODE REVIEW

**Comment by mrks** [comment]
Something in here is broken :D

**Comment by dey4ss** [comment]
> 
> 
> Something in here is broken :D

I hope not, besides a hash issue with std libraries that I hope to be able to fix once CI reaches the Mac stage.

**Comment by mrks** [comment]
Github tells me `+7,030 −5,434` and a long list of conflicts.

**Comment by dey4ss** [comment]
> 
> 
> Github gives me `+7,030 −5,434` and a long list of conflicts.

Yes, those are the cache meta tables for the BP and I guess their branch diverged from the master.

**Pull request closed without merging**
