### PR TITLE
Generate comparative graphs for multi-threaded benchmark results (Python script)

### PR DESCRIPTION
**Pull request by lanice**
This is basically a follow-up to the benchmark_multithreaded.py script I've added a while ago.

This PR adds the Python script `scripts/compare_benchmarks_multithreaded.py`. It takes multiple result folders (as created by `scripts/benchmark_multithreaded.py`) as arguments and creates two graphs, one to compare the performance (queries/s), and one to compare the scale factor of the results.

If, for example, we ran the multi-threaded benchmark script two times (for a subset of queries here), and store the results in the directories `results/old` and `results/new`, then with the following command:
```
python3 ./scripts/compare_benchmarks_multithreaded.py results/old results/new
```
we'd get the following two graphs:
The comparison of performance:
benchmark_comparison_performance

The comparison of scale-up:
benchmark_comparison_scaleup

This works for more results as well, if we want to compare 3 or more different results.

### CODE REVIEW

**Comment by Bouncner** [comment]
What is a “scale up factor”?

**Comment by mrks** [comment]
Couple of comments would be nice.

> What is a “scale up factor”?

@lanice - this is your chance to test if your explanation will be understood by others ;)

**Comment by lanice** [comment]
I updated the example graphs.
I also took out the average scale factor, since it does not really make sense in this context.

**Comment by mrks** [comment]
Mmmh, scale factor is already "taken" in the context of the TPC-H. Multithreadingbility maybe? :D

**Comment by lanice** [comment]
> Mmmh, scale factor is already "taken" in the context of the TPC-H. Multithreadingbility maybe? :D

Oh right, didn't think about that.... Hm, multithreadingbility sounds a a bit weird... :sweat_smile: In that case, maybe just scale-up?

**Comment by Bouncner** [comment]
Scale-Up does not say anything about the number being a factor.

"scalability factor" exists in related work, but is not really a perfect term for it either. :-/

**Comment by lanice** [comment]
Arg.. We could name it after what it does specifically:
Performance dy/dx, relative to single-threaded

**Comment by Bouncner** [comment]
What is “performance” on what are dx/dy?

**Comment by lanice** [comment]
> What is “performance” on what are dx/dy?

dy = throughput difference
dx = number of cores difference

Change in throughput-per-core, relative to single-threaded

**Comment by lanice** [comment]
I updated the graph to a more readable variant (as discussed earlier). y-axis of the second graph now showing the "Throughput per core, relative to single-threaded".

**Comment by Bouncner** [comment]
For the second graph: what about "Throughput (queries per second and core) \n (relative to single-threaded without scheduler)" to (i) be consistent with the upper graph and (ii) signal that single-threaded can be faster than 1 core performance due to not using the scheduler.

**Comment by lanice** [comment]
Hmm, that would result in the two graphs having different meanings for "Throughput", right? First graph, Throughput (queries / s), second graph, Throughput (queries / s per core).

We could more the "per core" out of the braces maybe?
"Throughput (queries / s ) per core \n (relative to single-threaded without scheduler)"

**Comment by Bouncner** [comment]
Your last proposal sounds good to me.

**Pull request merged**
