### PR TITLE
Fix malloc include for macOS

### PR DESCRIPTION
**Pull request by TwoLaid**
The new `dbgen` wants to include `malloc.h`, but this header does not exist on macOS. Instead, the regular malloc from `stdlib.h` will be used.

### CODE REVIEW

**Comment by mrks** [comment]
Ah, I thought it was just on my secondary laptop and included it by hand. Thanks.

**Comment by mrks** [comment]
It looks like CI doesn't like this. Is this a general problem with pulls from other repos? If so, we should fix that before the groups start working

**Comment by TwoLaid** [comment]
I have had the same problem the last time I opened a PR from my fork, but I assumed it was a glitch. I guess not.

**Comment by mrks** [comment]
Please don't change this PR. I'm trying to convince Jenkins to build this.

**Comment by mrks** [comment]
Please merge the current master. The new Jenkinsfile in there should fix this.

**Pull request merged**
