### PR TITLE
No more SOURCE_FILE_SIZE

### PR DESCRIPTION
**Pull request by mrzzzrm**
This was causing troubles when building with ninja. 

We did this: `#define TRIMMED_FILENAME (__FILE__ + SOURCE_PATH_SIZE)`

In make builds, `__FILE__` was, e.g., `/home/user/hyrise/lib/src/lol.cpp`. In ninja, it is just `src/lol.cpp`. In both cases, `SOURCE_PATH_SIZE` was the length of `/home/user/hyrise` and you cannot skip that many chars in `lol.cpp`.

Thus I removed it. Yes, this will make Assert error messages slightly longer, but no, I don't think that's a problem. This is once again prove that everything you do in a CMake file will sooner or later come back at you. We should have a VERY good reason for each line in your cmake setup.

### CODE REVIEW

**Comment by Bensk1** [comment]
Nice that it makes building with ninja easier!

**Comment by mrzzzrm** [comment]
In my opinion, trimming a path is not worth the extra compiler argument and the special handling in the cmake setup when the build is configured with ccache.

Compromise: Take `/home/user/code/hyrise-checkout/src/lib/file.cpp`, look up whether the path contains `src` and if it does, trim everything before it?

**Comment by mrks** [comment]
Reason I'd like to keep the previous behavior is also for Jenkins, where we otherwise end up with multi-line, random workspace directories.

The suggestion works for me as well. Let's check for `/src/` though.

**Comment by mrzzzrm** [comment]
Done

**Comment by mrks** [comment]
Donstig enough for me, but not for the CI :/

**Pull request merged**
