### PR TITLE
Fix NUMAPlacementManager on system with only one node

### PR DESCRIPTION
**Pull request by lanice**

### CODE REVIEW

**Comment by mrzzzrm** [comment]
This is effectively reverting #563 and will therefore re-trigger #562. We need a different solution here.

My stance is that all NUMA functionality should also be executable on systems with just one node (i.e. everyone's dev machines) - we should create an abstraction powerful enough to cover this. In this case - imo - this means fixing `inverted_entropy` regarding the issue described in #562. Problem is I have no idea what this method is doing and why.

**Comment by mrks** [comment]
What is the NPM supposed to do if there is only one NUMA node. We can't do any migrations and that's basically the only job of the NPM.

**Comment by mrzzzrm** [comment]
Of course it shouldn't do anything. It should **just not break**

**Comment by mrks** [comment]
But should we "create [a powerful] abstraction" only to make something work that will not do anything?

**Comment by lanice** [comment]
It is supposed to not crash. We have two options 

- Remove the NUMA libs from the install script, and ALSO check if the system is a NUMA system (or if it has only one node) during the CMake step with some sketchy bash commands
- Clean up the code so that it works with only one node.

Why should we introduce a restriction for one-node instead of fixing the problem? Does it cause that much overhead to not do anything on a one node system?

**Comment by lanice** [comment]
In my opinion having a system that works correctly in all cases is better than just work around edge cases

**Comment by lanice** [comment]
And for now, as @mrzzzrm said, maybe we don't need a powerful abstaction immediately, but just fix the inverted shannon entropy calculation regarding the division by zero.

**Comment by mrzzzrm** [comment]
By saying "a powerful abstraction" I didn't mean to imply that this would have to be a lot of work. Sorry. 

Our goals should be to have a code base that can deal with some simple edge cases and having just one node is one of them. And in this particular case we just need to fix that bloody inverted entropy thing.

**Comment by mrks** [comment]
I am all for fixing that thing. We should probably return 0, because then this will always be false:

```
  // Migrations are only considered when the imbalance between the NUMA nodes is high enough.
  if (node_info.imbalance > _options.imbalance_threshold && node_info.cold_nodes.size() > 0) {
```

At some point, we will have to stop though. We cannot perform any migrations, so I am not sure why we should spend any time running a thread that calculates which migrations might be possible.

**Comment by mrzzzrm** [comment]
The thread actually being executed is the fault of whoever called `resume()` and that's only happening in the tests right now.

**Comment by mrks** [comment]
Then shouldn't we fix that as well?

```
void NUMAPlacementManager::resume() {
  if (_topology->nodes().size()) return;
  // [...]
```

**Comment by mrzzzrm** [comment]
Returning 0 seems like it should work and it could even be semantically correct (0 "imbalance" if there is just one node, yeah, that could make sense).

(Just saw that `MigrationPreparationTask` are Tasks, but instead of scheduling them they are `execute()`d on a normal thread. Ouch...)

"Then shouldn't we fix that as well?" Imo a clean API wouldn't do that. Having a `resume()` method that under certain circumstances doesn't do anything seems unclean to me (and would result in less coverage on my machine than on the build servers). The caller should check whether running the NPM makes sense or just live with the overhead.

**Comment by lanice** [comment]
Just did my share of research on maximum entropy and entropy in general as well, yes 0 should be good in that case. That the maximum entropy comes out zero (which we then try to divide by) makes sense as well, since the most imbalanced temperature distribution of one node still comes out to an imbalance of zero.

**Comment by mrks** [comment]
As far as the tasks running in a regular thread goes: I think this is because our scheduler doesn't have any notion of "run this every x seconds/minutes". For that, using a thread seems ok to me. We might want to replace the `execute()` in the NPM with `schedule` though.

**Comment by mrks** [comment]
We can continue discussing this, but I'll merge this now, because it keeps people from running the tests.

**Pull request merged**
