### PR TITLE
Remove build-essential from install script, dependencies and docker

### PR DESCRIPTION
**Pull request by Bensk1**
Build-essential does depend on gcc-7 which is then unnecessary installed because our scripts install gcc-8 anyways.

I removed build-essential from the install script on a fresh Ubuntu 18.04 image. Either we do not need any of the packages or Ubuntu 18.04 comes with them anyway.

I believe we had to add build-essential for lib tool or something similar to be able to build a former external dependency.

### CODE REVIEW

**Comment by Bensk1** [comment]
No, I did not yet. My docker test machine (imdmresearch-keller) is down now. Can we use the CI for that?

**Comment by Bensk1** [comment]
CI complained the second time in a row about `ServerTestRunner.TestMultipleConnections`

**Comment by mrks** [comment]
sure. `ssh imresx01`

**Comment by Bensk1** [comment]
Docker seems to work without that. However, other packages, e.g., llvm-6 install gcc-7 anyway. The `update-alternatives` command seems to work and Cmake should automatically pick gcc-8 afterwards.

**Pull request merged**
