### PR TITLE
AbstractOperator::type() to query concrete type 

### PR DESCRIPTION
**Pull request by mrzzzrm**
we have the same in `AbstractLQPNode`. #NeedThisForMyMA

### CODE REVIEW

**Comment by mrks** [comment]
Could you please remind me why you prefer this over RTTI?

**Comment by mrzzzrm** [comment]
* If you have 20 sub types and do it via rtti, wouldn't you have to do 20 dynamic_casts to find the last type instead of one switch?
* unordered_map support enum class as key, but not type_info. 
* personal preference

**Comment by mrks** [comment]
`typeid(some_operator) == typeid(TableScan)` seems to me to be just as good as `some_operator.type() == OperatorType::TableScan`. It keeps us from maintaining the list of types and prevents any type of mismatch.

Why doesn’t `unordered_map` support `type_info`? [This](https://stackoverflow.com/questions/3552135/does-c11-provide-hashing-functions-for-stdtype-info) looks like it does.

**Comment by mrzzzrm** [comment]
mmmh, tbh the unordered_map argument was made up on the way, seems like you can use the type_info-pointer as a key. Ugly as hell to read, but you could.

What I don't like about using RTTI is the looong chain of branches that need to be checked just to identify the correct type. Switch just does a jump table lookup.

**Comment by mrzzzrm** [comment]
Also, compilers tell you if you missed an element when switching enum-class, dynamic-cast chains won't

**Comment by mrks** [comment]
I can live with this - just wanted to make sure that we have good reasons to duplicate information that is technically already there. I’ll have a look at the changes right now.

**Comment by mrzzzrm** [comment]
@mrks making type virtual would be way more text than this way is, that's my reasoning. Text adds noise. Noise confuses people, me first and foremost.

**Pull request merged**
