### PR TITLE
[WIP] Data-Induced Predicates

### PR DESCRIPTION
**Pull request by Dencrash**
This pull request is used to evaluate the necessary changes to bring Data-Induced Predicates to Hyrise, observe the current code quality and use a convenient place to notes from code reviews.

Currently, the code has not yet run-trough the linter.

### CODE REVIEW

**Comment by Bensk1** [comment]
@PeterTsayun or @Dencrash, is this ready for having a look at it?

**Comment by Bensk1** [comment]
Could you please merge the current master? Otherwise the CI will not run.

**Comment by Bensk1** [comment]
The current master fixes the DockerHub problem, could you please merge it?

**Comment by Bensk1** [comment]
> The current master fixes the DockerHub problem, could you please merge it?

Ping.

**Comment by PeterTsayun** [comment]
> Ping

Master is merged, sorry that it took so long :crying_cat_face:

**Comment by Bensk1** [comment]
> Master is merged, sorry that it took so long 😿

Thanks a lot!

**Comment by Bensk1** [comment]
Replaced by #2374

**Pull request closed without merging**
