### PR TITLE
Extend compare_benchmarks.py script with --ignore-naming parameter

### PR DESCRIPTION
**Pull request by Miroka96**
Regarding comparison of benchmark results from FileBasedBenchmarks

Previously it was only possible to compare results of the same benchmark. This failed in our setup where we rewrote SQL queries and stored them in a second file. When running the benchmarks, this caused a different name, although the queries were doing the same in two different manners.

To be able to compare them anyway using scripts/compare_benchmarks.py just add the parameter --ignore-naming

### CODE REVIEW

**Comment by Bouncner** [comment]
Please add a description.

**Comment by Miroka96** [comment]
How can I retrigger Jenkins?

**Comment by Bouncner** [comment]
`git commit --allow-empty -m 'Trigger CI'`

**Comment by Bensk1** [comment]
Has anyone else ever encountered this problem? Do we really need it?

**Comment by mrks** [comment]
Ok, the explanation in the description makes sense. Instead of adding a parameter that we are parsing by hand and that is semi-documented, why don't we simply print both query names (maybe in red?) in cases where the names don't match?

**Comment by Miroka96** [comment]
Sorry for my delay in answering...
Do you mean, just set the parameter by default and do not fail, if the names differ? This would be a solution

**Comment by mrks** [comment]
Almost - I meant not having a parameter/flag/variable at all and simply print a warning.

**Comment by mrks** [comment]
I'm trying to reduce the list of open PRs, so I took the liberty of making that change myself.

**Pull request closed without merging**
