### PR TITLE
Single-Value Optimization for cuckoo hash

### PR DESCRIPTION
**Pull request by mrks**
In many cases, we only have a single entry per value. For TPC-H, only 5% would call `PosList::push_back`. By having this variant, we can save us the cost of allocating heap storage for a single value.

### CODE REVIEW

**Comment by mrks** [comment]
Because of [this clang bug](https://bugs.llvm.org/show_bug.cgi?id=33222), we would need to update gcc (to get a current libstdc++ with a workaround).

**Comment by mrks** [comment]
Yo dawg, I heard you like compiler bugs. Looks like gcc-7 has a regression...

```
../../../src/lib/operators/table_scan/column_comparison_table_scan_impl.cpp:71:75: internal compiler error: in tsubst_copy, at cp/pt.c:15035

               this->_binary_scan(comparator, left_it, left_end, right_it, chunk_id, *matches_out);

                                                                           ^~~~~~~~

```

**Comment by mrks** [comment]
Ok, so because of a clang bug, we need to update gcc to 8+. gcc 8 has a [different bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86740), that keeps us from building Hyrise (unrelated to this PR).

This in on hold for now until we have news from GCC.

**Comment by mrks** [comment]
```
 Benchmark | prev. iter/s | new iter/s | change
-----------+--------------+------------+---------------
 TPC-H 1   | 0.84         | 0.843      | +0%
 TPC-H 2   | 0.027        | 0.029      | +5%
 TPC-H 3   | 12.498       | 12.355     | -1%
 TPC-H 4   | 0.008        | 0.008      | -2%
 TPC-H 5   | 5.973        | 6.474      | +8%
 TPC-H 6   | 35.983       | 35.861     | -0%
 TPC-H 7   | 0.888        | 0.904      | +2%
 TPC-H 8   | 0.007        | 0.007      | -2%
 TPC-H 9   | 2.061        | 2.109      | +2%
 TPC-H 10  | 10.853       | 11.079     | +2%
 TPC-H 11  | 27.521       | 26.931     | -2%
 TPC-H 12  | 5.261        | 5.284      | +0%
 TPC-H 13  | 13.709       | 13.088     | -5%
 TPC-H 14  | 19.644       | 19.819     | +1%
 TPC-H 15  | 0.084        | 0.082      | -2%
 TPC-H 16  | 3.098        | 3.091      | -0%
 TPC-H 17  | 0.002        | 0.002      | +18%
 TPC-H 18  | 0.012        | 0.012      | -0%
 TPC-H 19  | 0.637        | 0.633      | -1%
 TPC-H 20  | 0.006        | 0.007      | +17%
 TPC-H 21  | 0.039        | 0.039      | -0%
 TPC-H 22  | 0.39         | 0.456      | +17%
 average   |              |            | +3%
```

Some significant improvements, no significant regressions.

**Comment by Bouncner** [comment]
I’d expected less memory wasting but not a runtime improvement. Is that reproducible?
My (not really scientific) benchmarks showed a slight performance drop using std::variant.

**Comment by mrks** [comment]
What did you measure?

The problem is not the memory itself, but the number of dynamic allocations needed. Less allocations = better performance.

**Comment by Bouncner** [comment]
I micro benchmarked a few k insert with skewed number of positions/key (mostly only one, but sometimes hundreds) und 1M find operations.

But as of now, only ints. Will move to RowID next days. Goal was to get an idea about the Cockuu map’s performance.

I’ll show you tomorrow.

**Comment by mrks** [comment]
After the discussion: The 5% were measured on a different data structure. We shall look into alternative hash tables later.

**Pull request merged**
