### PR TITLE
Project/#1 create index

### PR DESCRIPTION
**Pull request by simonstadlinger**

### CODE REVIEW

**Comment by Bouncner** [comment]
?

**Comment by simonstadlinger** [comment]
@Bouncner This is WIP. I just saw that there is a label for this kind of pull request. We want our project coordinator @mweisgut to have a look at it. Apologies for the confusion

**Comment by Bouncner** [comment]
To avoid having too many open (not yet reviewable) PRs here, we prefer that you work on your fork with your advisor. Once you need feedback from other people, a draft PRs is totally fine (see slide #24, week 7).

**Comment by simonstadlinger** [comment]
All right!

**Pull request closed without merging**
