### PR TITLE
Fix AggregateTest

### PR DESCRIPTION
**Pull request by mrzzzrm**
1. I have no idea what `test_output` did with that set of ColumnIDs, except randomly scanning on Columns. How did that make sense? I changed the function to perform just a single scan to produce the reference table.
2. I have no clue why this never came up in memcheck-CI

Anyway: Valgrind just locally informed me of a uninitialised variable in
```c++
-      for (const auto& agg : aggregates) {
-        ref_columns.insert(*agg.column);
-      }
```

and sure enough, a test introduced two months ago (@mrks) hands in a std::nullopt here, from which 
`*agg.column` tries to retrieve a value.

```c++
TEST_F(OperatorsAggregateTest, TwoAggregateEmptyTable) {
  auto filtered = std::make_shared<TableScan>(_table_wrapper_1_2, ColumnID{0}, PredicateCondition::LessThan, 0);
  filtered->execute();
  this->test_output(filtered,
                    {{ColumnID{1}, AggregateFunction::Max},
                     {ColumnID{2}, AggregateFunction::Count},
                     {std::nullopt, AggregateFunction::Count}},
                    {}, "src/test/tables/aggregateoperator/0gb_3agg/max_count_count_empty.tbl", 1);
}
```

### CODE REVIEW

**Comment by Bensk1** [comment]
I agree that the old version does not seem to make too much sense, but is this fixed TableScan hack the best we can do?

**Comment by mrzzzrm** [comment]
To produce ReferenceColumns, you mean? It doesn't get MUCH better. Sort maybe.

**Comment by Bensk1** [comment]
Yes, to produce ReferenceColumns.

**Comment by mrzzzrm** [comment]
I thought about a TurnInputIntoReferencesOperator, but those thoughts haven't progressed very far yet.

**Pull request merged**
