### PR TITLE
WIP Introduce BaseTypedColumn

### PR DESCRIPTION
**Pull request by adi64**
This introduces `BaseTypedColumn<T>` as additional *virtual* base class for all concrete column types. 

Mainly, this is used to introduce two new methods:
```
virtual const optional<T> BaseTypedColumn::get_typed_value(const ChunkOffset chunk_offset) const
virtual void append_typed_value(const std::optional<T> value_or_null)
```

This is similar to the widely-loved
`virtual const BaseColumn::AllTypeVariant operator[](const ChunkOffset chunk_offset) const`
and still incurs the cost of a virtual method call, but does not have to deal with `AllTypeVariant`s. It is therefore a compromise solution for situations in which the concrete type is not known and using `resolve_column_type` is too expensive (mainly `ReferenceColumnIterable`, but `Sort` should also be able to benefit from this (ref #768))

This creates a [deadly diamond of death](https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem). I am not really happy with how the concrete column constructors now look like. Suggestions?

Unfortunately, even if we know that every column instance is also a BaseTypedColumn, `static_cast` does not work and we *do* need a `dynamic_cast`, since we're casting to a *virtual* base class.

TODO-ish:
- implement `append_typed_value()`
- ~~~compare / combine with #793~~~ (will be done later, if we have PosList meta information)
- ~~~Adapt PosList to have meta information (e.g. only one chunk, all columns have same encoding, ...)~~~ (in progress, will be done later if we actually want that - I think that is a separate issue)

## Benchmarks (on sidon, based on mid-July `master`)
### ReferenceColumnIterable with dynamic_cast on every access
```
 Benchmark | prev. iter/s | new iter/s | change                                                                                                                                                                                               
 -----------+--------------+------------+---------------
 TPC-H 1   | 0.049        | 0.032      | -35%
 TPC-H 3   | 1.323        | 0.723      | -45%
 TPC-H 5   | 0.035        | 0.008      | -78%
 TPC-H 6   | 5.505        | 4.636      | -16%
 TPC-H 7   | 0.139        | 0.093      | -33%
 TPC-H 9   | 0.024        | 0.005      | -77%
 TPC-H 10  | 0.896        | 0.668      | -25%
 TPC-H 13  | 0.758        | 0.502      | -34%
 average   |              |            | -43%
```
(wtf!)

### ReferenceColumnIterable with column cache (lazy)
```
 Benchmark | prev. iter/s | new iter/s | change                                                                                                                                                                                               
-----------+--------------+------------+--------------
 TPC-H 1   | 0.049        | 0.048      | -2% 
 TPC-H 3   | 1.323        | 1.232      | -7% 
 TPC-H 5   | 0.035        | 0.032      | -8% 
 TPC-H 6   | 5.505        | 5.173      | -6% 
 TPC-H 7   | 0.139        | 0.146      | +6% 
 TPC-H 9   | 0.024        | 0.023      | -3% 
 TPC-H 10  | 0.896        | 0.905      | +1% 
 TPC-H 13  | 0.758        | 0.787      | +4% 
 average   |              |            | -2% 
```
(wtf!)

### ReferenceColumnIterable with pre-filled column cache
```                                                                                                                                                                                                                                         
 Benchmark | prev. iter/s | new iter/s | change                                                                                                                                                                                               
-----------+--------------+------------+---------------
 TPC-H 1   | 0.049        | 0.05       | +3%  
 TPC-H 3   | 1.323        | 1.441      | +9%  
 TPC-H 5   | 0.035        | 0.048      | +37% 
 TPC-H 6   | 5.505        | 5.774      | +5%  
 TPC-H 7   | 0.139        | 0.149      | +8%  
 TPC-H 9   | 0.024        | 0.038      | +58% 
 TPC-H 10  | 0.896        | 0.951      | +6%  
 TPC-H 13  | 0.758        | 0.801      | +6%  
 average   |              |            | +16% 
```

### CODE REVIEW

**Comment by adi64** [comment]
@mrks @Bensk1 This is ready for a first round of review :)

**Comment by mjendruk** [comment]
Hi! Just as an alternative, you could implement something like an "typed accessor" and use the `resolve_column_type` method to create the appropriate one. Then you store the accessors as you would store the `BaseTypedColumn`. Since you resolve the type anyway in the `ReferenceColumnIterable`. This way you would avoid virtual inheritance.

It could look like this:

```c++
template <typename T>
class BaseAccessor
{
    virtual const T& access(size_t i) const = 0;
};

template <typename T, typename ColumnT>
class Accessor : public BaseAccessor
{
    const T& access(size_t i) const 
    {
        return _column.get(i);
    }

public:
    std::shared_ptr<ColumnT> _column;
};
```

**Comment by mrks** [comment]
Here is an idea on how to do this without virtual inheritance. We still have a diamond, but it comes without the problems:

https://gist.github.com/mrks/5be9db646e1db9316e4976a6bd127f1b

**Comment by mrks** [comment]
After getting some more input, let's go with #1063

**Pull request closed without merging**
