### PR TITLE
Standardize template stuff

### PR DESCRIPTION
**Pull request by timzimmermann**
I was annoyed by our inconsistent use of various template helpers such as `std::enable_if` and `std::enable_if_t`.
So I set out to unify it, which worked in all but [one case](https://github.com/hyrise/hyrise/blob/master/src/lib/expression/evaluation/expression_evaluator.cpp#L825):

```c++
if constexpr (Functor::template supports<Result, LeftDataType, RightDataType>::value) {
...
}
```

I tried changing it to 

```c++
if constexpr (Functor::template supports_v<Result, LeftDataType, RightDataType>) {
...
}
```

after adding 

```c++
template <typename Result, typename ArgA, typename ArgB>
inline static constexpr bool supports_v = supports<Result, ArgA, ArgB>::value;
```

to all the structs defined in [expression_functors.hpp](https://github.com/hyrise/hyrise/blob/master/src/lib/expression/evaluation/expression_functors.hpp), but that does not compile.
Maybe any of the template wizards have an idea why and cannot wait to teach me?

### CODE REVIEW

**Comment by mrks** [comment]
What's the error message?

**Comment by mrks** [comment]
`::value` is a bool. Try removing `typename`. Otherwise I'll have a look once I have a compiler at hand

**Comment by timzimmermann** [comment]
> `::value` is a bool. Try removing `typename`. Otherwise I'll have a look once I have a compiler at hand

I think you are referring to my initial reply, which I had to update because that was a different thing I tried.
`Functor` is a template parameter, and changing `Functor::template supports_v...` to `Functor::supports_v...` results in this error message:

```c++
/Users/tim/Documents/work/2018_epic/hyrise/src/lib/expression/evaluation/expression_evaluator.cpp:825:28: error: use
      'template' keyword to treat 'supports_v' as a dependent template name
    if constexpr (Functor::supports_v<Result, LeftDataType, RightDataType>) {
                           ^
                           template
/Users/tim/Documents/work/2018_epic/hyrise/src/lib/expression/evaluation/expression_evaluator.cpp:863:28: error: use
      'template' keyword to treat 'supports_v' as a dependent template name
    if constexpr (Functor::supports_v<Result, LeftDataType, RightDataType>) {
                           ^
                           template
/Users/tim/Documents/work/2018_epic/hyrise/src/lib/expression/evaluation/expression_evaluator.cpp:825:19: error:
      constexpr if condition is not a constant expression
    if constexpr (Functor::supports_v<Result, LeftDataType, RightDataType>) {
                  ^
/Users/tim/Documents/work/2018_epic/hyrise/src/lib/expression/evaluation/expression_evaluator.cpp:132:56: note: in
      instantiation of function template specialization
      'opossum::ExpressionEvaluator::_evaluate_binary_with_default_null_logic<int,
      opossum::STLComparisonFunctorWrapper<std::equal_to> >' requested here
    case PredicateCondition::Equals:            return _evaluate_binary_with_default_null_logic<ExpressionEvalu...
                                                       ^
```

Feel free to stop by when you find some time, I'd appreciate it.

**Comment by mrks** [comment]
The compiler complains even if we replace `supports<Result, ArgA, ArgB>::value` with `true`. At a first glance, I can't see anything wrong with the code.

According to Google, two people have experienced "constexpr if condition is not a constant expression" so far, and we know one of them. Have you tried this with gcc? You could also try to reduce the problem to an SSCCE.

**Comment by timzimmermann** [comment]
> The compiler complains even if we replace `supports<Result, ArgA, ArgB>::value` with `true`. At a first glance, I can't see anything wrong with the code.

Not sure, if @mrzzzrm will take a look at it, but otherwise I'd say we go ahead and merge it as is.

> According to Google, two people have experienced "constexpr if condition is not a constant expression" so far, and we know one of them. Have you tried this with gcc? You could also try to reduce the problem to an SSCCE.

I have not tried with gcc, and I probably won't find the time to do this or an SSCCE in the near future.

**Pull request merged**
