### PR TITLE
Fix ExpressionResultNullableSeries::is_nullable()

### PR DESCRIPTION
**Pull request by mrzzzrm**

### CODE REVIEW

**Comment by mrks** [comment]
(No need to work on this now, I'm on it)

**Comment by mrzzzrm** [comment]
For LiteralViews the nullability is indeed checked at runtime. This is because having an explicit NullLiteralView-type would noticeably increase the amount of code generated - and I think we can afford to trade a bit of performance for smaller binaries when literals are involved. 

So, I wouldn't write `if constexpr (left_view.is_null(chunk_offset)) {` but just `if(left_view.is_null(chunk_offset)) {` and rely on the compiler to detect the cases where `left_view.is_null(chunk_offset)` is fixed true or false at compile time. The benchmarks I did when implementing the expressions seemed to indicate that this works.

**Comment by mrks** [comment]
It looks like this is not needed for what we are doing in #1160. If you have other reasons why this should be done, please reopen and I'll approve.

**Comment by mrzzzrm** [comment]
It should be merged because it potentially allows the compiler to remove branches that depend on `view.is_nullable()`

**Pull request merged**
