### PR TITLE
Removed superfluous file removal during `SetUp `

### PR DESCRIPTION
**Pull request by tjjordan**
Minor change to the BinaryWriterTest with regard to Issue #2472:
- Removed unnecessary file removal in test setup

The tests still run successful and no files exist after finishing the tests.

### CODE REVIEW

**Comment by mweisgut** [comment]
I was also having this in mind and yes, I think an error could occur in that case. And sure, with the file removal in the setup function, we could avoid such an error. However, if a segfault happens during the test suite execution, the fault is probably at a different location which should be fixed in that case.

**Comment by dey4ss** [comment]
My question was just out of curiosity, and I don't know if we also cover this for the csv writer tests. I'm fine with removing the initial test file removal (what a sentence 😅): if a segfault happens during auch a test, it should be a problem with the binary writer and the developer should know best what happend where.

**Comment by Bouncner** [comment]
@tjjordan : I see the manual format run (#c4ce917). Do I get that right, that the format script of the CI did not complain but your "local" clang-format did the "right thing"?

**Comment by tjjordan** [comment]
@Bouncner Yep, this is what happened.

**Pull request merged**
