### PR TITLE
Enable binary table loading for TPC-C in server

### PR DESCRIPTION
**Pull request by Bouncner**
This PR enables binary table loading for TPC-C in the `hyriseServer` binary. #2337 enabled it.

### CODE REVIEW

**Comment by Bensk1** [comment]
I thought it was disabled because we couldn't do it. That's not the case? Just disabling the check is sufficient?

**Comment by Bouncner** [comment]
@2337 enabled it.

<details><summary>Master:</summary>

```
Martin.Boissier@nemea:~/hyrise$ numactl -m 3 -N 3 ./rel_clang/hyriseServer --benchmark_data TPCC:1
- Loading/Generating tables
- Loading/Generating tables done (3 s 305 ms)
- Encoding tables (if necessary) and generating pruning statistics
-  Encoding 'WAREHOUSE' - encoding applied (898 µs 227 ns)
-  Encoding 'DISTRICT' - encoding applied (992 µs 707 ns)
-  Encoding 'NEW_ORDER' - encoding applied (4 ms 813 µs)
-  Encoding 'ORDER' - encoding applied (38 ms 681 µs)
-  Encoding 'HISTORY' - encoding applied (48 ms 393 µs)
-  Encoding 'ORDER_LINE' - encoding applied (110 ms 639 µs)
-  Encoding 'ITEM' - encoding applied (206 ms 934 µs)
-  Encoding 'CUSTOMER' - encoding applied (208 ms 481 µs)
-  Encoding 'STOCK' - encoding applied (628 ms 536 µs)
- Encoding tables and generating pruning statistic done (630 ms 147 µs)
- Adding tables to StorageManager and generating table statistics
-  Added 'DISTRICT' (452 µs 595 ns)
-  Added 'WAREHOUSE' (2 ms 83 µs)
-  Added 'HISTORY' (41 ms 390 µs)
-  Added 'NEW_ORDER' (42 ms 831 µs)
-  Added 'CUSTOMER' (135 ms 701 µs)
-  Added 'ORDER' (159 ms 260 µs)
-  Added 'ITEM' (167 ms 334 µs)
-  Added 'STOCK' (214 ms 752 µs)
-  Added 'ORDER_LINE' (380 ms 490 µs)
- Adding tables to StorageManager and generating table statistics done (380 ms 660 µs)
- No indexes created as --indexes was not specified or set to false
Server started at 0.0.0.0 and port 5432
Run 'psql -h localhost 0.0.0.0' to connect to the server
^C
Martin.Boissier@nemea:~/hyrise$ numactl -m 3 -N 3 ./rel_clang/hyriseServer --benchmark_data TPCC:1
- Loading/Generating tables
- Loading/Generating tables done (3 s 321 ms)
- Encoding tables (if necessary) and generating pruning statistics
-  Encoding 'DISTRICT' - encoding applied (861 µs 639 ns)
-  Encoding 'WAREHOUSE' - encoding applied (921 µs 577 ns)
-  Encoding 'ORDER' - encoding applied (14 ms 163 µs)
-  Encoding 'HISTORY' - encoding applied (47 ms 717 µs)
-  Encoding 'NEW_ORDER' - encoding applied (105 ms 620 µs)
-  Encoding 'ITEM' - encoding applied (155 ms 972 µs)
-  Encoding 'CUSTOMER' - encoding applied (206 ms 906 µs)
-  Encoding 'ORDER_LINE' - encoding applied (436 ms 317 µs)
-  Encoding 'STOCK' - encoding applied (727 ms 825 µs)
- Encoding tables and generating pruning statistic done (729 ms 424 µs)
- Adding tables to StorageManager and generating table statistics
-  Added 'WAREHOUSE' (428 µs 144 ns)
-  Added 'NEW_ORDER' (1 ms 318 µs)
-  Added 'DISTRICT' (2 ms 320 µs)
-  Added 'HISTORY' (37 ms 997 µs)
-  Added 'ORDER' (40 ms 97 µs)
-  Added 'CUSTOMER' (86 ms 224 µs)
-  Added 'ITEM' (167 ms 212 µs)
-  Added 'STOCK' (355 ms 540 µs)
-  Added 'ORDER_LINE' (355 ms 630 µs)
- Adding tables to StorageManager and generating table statistics done (355 ms 752 µs)
- No indexes created as --indexes was not specified or set to false
Server started at 0.0.0.0 and port 5432
Run 'psql -h localhost 0.0.0.0' to connect to the server
```

</details>

<details><summary>This PR:</summary>
```
Martin.Boissier@nemea:~/hyrise$ numactl -m 3 -N 3 ./rel_clang/hyriseServer --benchmark_data TPCC:1
- Loading/Generating tables
- Loading/Generating tables done (3 s 368 ms)
- Encoding tables (if necessary) and generating pruning statistics
-  Encoding 'WAREHOUSE' - encoding applied (986 µs 106 ns)
-  Encoding 'DISTRICT' - encoding applied (1 ms 4 µs)
-  Encoding 'NEW_ORDER' - encoding applied (30 ms 618 µs)
-  Encoding 'ORDER' - encoding applied (30 ms 968 µs)
-  Encoding 'HISTORY' - encoding applied (107 ms 156 µs)
-  Encoding 'ORDER_LINE' - encoding applied (107 ms 311 µs)
-  Encoding 'ITEM' - encoding applied (156 ms 24 µs)
-  Encoding 'CUSTOMER' - encoding applied (207 ms 375 µs)
-  Encoding 'STOCK' - encoding applied (570 ms 667 µs)
- Encoding tables and generating pruning statistic done (572 ms 284 µs)
- Writing tables into binary files if necessary
-  Writing 'NEW_ORDER' into binary file "tpcc_cached_tables/sf-1/NEW_ORDER.bin" (379 µs 459 ns)
-  Writing 'ORDER_LINE' into binary file "tpcc_cached_tables/sf-1/ORDER_LINE.bin" (34 ms 142 µs)
-  Writing 'DISTRICT' into binary file "tpcc_cached_tables/sf-1/DISTRICT.bin" (141 µs 168 ns)
-  Writing 'STOCK' into binary file "tpcc_cached_tables/sf-1/STOCK.bin" (60 ms 281 µs)
-  Writing 'CUSTOMER' into binary file "tpcc_cached_tables/sf-1/CUSTOMER.bin" (34 ms 738 µs)
-  Writing 'WAREHOUSE' into binary file "tpcc_cached_tables/sf-1/WAREHOUSE.bin" (134 µs 905 ns)
-  Writing 'ORDER' into binary file "tpcc_cached_tables/sf-1/ORDER.bin" (658 µs 8 ns)
-  Writing 'HISTORY' into binary file "tpcc_cached_tables/sf-1/HISTORY.bin" (2 ms 804 µs)
-  Writing 'ITEM' into binary file "tpcc_cached_tables/sf-1/ITEM.bin" (20 ms 836 µs)
- Writing tables into binary files done (154 ms 535 µs)
- Adding tables to StorageManager and generating table statistics
-  Added 'DISTRICT' (1 ms 6 µs)
-  Added 'NEW_ORDER' (1 ms 232 µs)
-  Added 'WAREHOUSE' (5 ms 221 µs)
-  Added 'HISTORY' (48 ms 949 µs)
-  Added 'CUSTOMER' (86 ms 483 µs)
-  Added 'ORDER' (135 ms 693 µs)
-  Added 'ITEM' (135 ms 712 µs)
-  Added 'STOCK' (209 ms 946 µs)
-  Added 'ORDER_LINE' (356 ms 499 µs)
- Adding tables to StorageManager and generating table statistics done (356 ms 644 µs)
- No indexes created as --indexes was not specified or set to false
Server started at 0.0.0.0 and port 5432
Run 'psql -h localhost 0.0.0.0' to connect to the server
^C
Martin.Boissier@nemea:~/hyrise$ numactl -m 3 -N 3 ./rel_clang/hyriseServer --benchmark_data TPCC:1
- Loading/Generating tables
-  Loading table 'STOCK' from cached binary "tpcc_cached_tables/sf-1/STOCK.bin" (115 ms 369 µs)
-  Loading table 'ORDER_LINE' from cached binary "tpcc_cached_tables/sf-1/ORDER_LINE.bin" (31 ms 963 µs)
-  Loading table 'ORDER' from cached binary "tpcc_cached_tables/sf-1/ORDER.bin" (460 µs 10 ns)
-  Loading table 'DISTRICT' from cached binary "tpcc_cached_tables/sf-1/DISTRICT.bin" (33 µs 320 ns)
-  Loading table 'CUSTOMER' from cached binary "tpcc_cached_tables/sf-1/CUSTOMER.bin" (29 ms 929 µs)
-  Loading table 'HISTORY' from cached binary "tpcc_cached_tables/sf-1/HISTORY.bin" (2 ms 228 µs)
-  Loading table 'NEW_ORDER' from cached binary "tpcc_cached_tables/sf-1/NEW_ORDER.bin" (142 µs 618 ns)
-  Loading table 'ITEM' from cached binary "tpcc_cached_tables/sf-1/ITEM.bin" (14 ms 524 µs)
-  Loading table 'WAREHOUSE' from cached binary "tpcc_cached_tables/sf-1/WAREHOUSE.bin" (27 µs 150 ns)
- Loading/Generating tables done (200 ms 787 µs)
- Encoding tables (if necessary) and generating pruning statistics
-  Encoding 'DISTRICT' - no encoding necessary (666 µs 47 ns)
-  Encoding 'ORDER' - no encoding necessary (607 µs 427 ns)
-  Encoding 'HISTORY' - no encoding necessary (761 µs 959 ns)
-  Encoding 'NEW_ORDER' - no encoding necessary (654 µs 150 ns)
-  Encoding 'CUSTOMER' - no encoding necessary (1 ms 223 µs)
-  Encoding 'STOCK' - no encoding necessary (6 ms 325 µs)
-  Encoding 'ITEM' - no encoding necessary (8 ms 15 µs)
-  Encoding 'ORDER_LINE' - no encoding necessary (27 ms 217 µs)
-  Encoding 'WAREHOUSE' - no encoding necessary (27 ms 367 µs)
- Encoding tables and generating pruning statistic done (27 ms 483 µs)
- Writing tables into binary files if necessary
- Writing tables into binary files done (24 µs 327 ns)
- Adding tables to StorageManager and generating table statistics
-  Added 'DISTRICT' (811 µs 637 ns)
-  Added 'WAREHOUSE' (992 µs 101 ns)
-  Added 'ORDER' (3 ms 129 µs)
-  Added 'NEW_ORDER' (125 ms 728 µs)
-  Added 'ITEM' (135 ms 408 µs)
-  Added 'CUSTOMER' (135 ms 565 µs)
-  Added 'HISTORY' (169 ms 324 µs)
-  Added 'STOCK' (216 ms 365 µs)
-  Added 'ORDER_LINE' (364 ms 369 µs)
- Adding tables to StorageManager and generating table statistics done (364 ms 491 µs)
- No indexes created as --indexes was not specified or set to false
Server started at 0.0.0.0 and port 5432
Run 'psql -h localhost 0.0.0.0' to connect to the server
```

</details>

**Comment by Bouncner** [comment]
> Does this mean that tables are cached by default for TPC-C? If yes, does this mean that we have to adapt tests, for example, in `scripts/test/hyriseBenchmarkTPCC_test.py`?

Yes, it's the same as with all other benchmarks. The mentioned test checks for `benchmark.expect_exact("Loading table 'NEW_ORDER' from cached binary")` in a second benchmark run to check that binary tables are generated and loaded.

**Comment by Bensk1** [comment]
If I see it correctly, the TPCH test does not cache binary tables in 3 out of 4 cases. The TPCC caches them for all cases now (which could be perfectly fine).

**Comment by Bouncner** [comment]
> If I see it correctly, the TPCH test does not cache binary tables in 3 out of 4 cases. The TPCC caches them for all cases now (which could be perfectly fine).

Good point. I'll take a look and might add the tests for TPC-H. I vaguely remember we had issues with concurrent tests, but as far as I can tell, all TPCH tests run within the cmake folders. So I don't see an issue there, at least not yet.

**Comment by Bouncner** [comment]
> If I see it correctly, the TPCH test does not cache binary tables in 3 out of 4 cases. The TPCC caches them for all cases now (which could be perfectly fine).

Added binary writing and loading checks. Not too happy with it as (I think) we cannot test that a certain line does not occur with pexpect. So with the current output, we cannot recognize if data was loaded or generated. But it's an improvement.

**Pull request merged**
