### PR TITLE
Remove two TPC-H hacks

### PR DESCRIPTION
**Pull request by mrks**

### CODE REVIEW

**Comment by mrks** [comment]
wat? 

```
Markus.Dreseler@nemea:~/hyrise$ ./build-release/hyriseConsole
HYRISE SQL Interface
Type 'help' for more information.

Hyrise is running a (release) build.

(release)> generate_tpch 0.1
Generating all TPCH tables (this might take a while) ...
(release)> SELECT c_count, count(*) as custdist FROM (SELECT c_custkey, count(o_orderkey) FROM customer left outer join orders on c_custkey = o_custkey AND o_comment not like '%special%request%' GROUP BY c_custkey) as c_orders (c_custkey, c_count) GROUP BY c_count ORDER BY custdist DESC, c_count DESC;
[PERF] [...]

=== Columns
```

Why isn't that working in the benchmark runner?

**Comment by Bouncner** [comment]
Sure about that query?
What are the two attributes doing after the group by?

**Comment by mrks** [comment]
They are column aliases for the subselect. That query works if I copy it into the console. oO

**Comment by mrks** [comment]
Ah, I think it's sqlite. Moved to #1180

**Comment by mrks** [comment]
Ah, I think it's sqlite. Moved to #1180

**Pull request closed without merging**
