### PR TITLE
Rename AST to Logical Query Plan (LQP)

### LINKED ISSUE #445: Change AST name to convey graph nature
@mrks wrote:

```

I don't even want to bring it up, that's why I'm adding this comment at the bottom: With the changes in this PR, we don't have an AST anymore. Technically, the tree is now a DAG. Do we want to change names? This will also come up once we touch the operator tree.

Also paging @Bensk1 @klauck @Bouncner
```

I would really like to go for `QueryGraph` or `QueryPlan` (name already taken :( ) with `AbstractQuery(Plan)Nodes` here, and refer to our Operators as the `Execution/OperatorGraph`. Mostly since that is what we're doing, we're "planning" the query. One might mistake it for the actual execution plan if we name it `QueryGraph/Plan` but then again, the Operator-Tree is a 1-1 mapping from the AST, with the exception of `_translate_aggregate_node()`.

(Maybe we could get rid of the logic in `_translate_aggregate_node()` and the bloody `AbstractOperator::recreate()` and just call the `ASTToOperatorTranslator0` to recreate Operator-Trees)

### PR DESCRIPTION
**Pull request by mrzzzrm**
Fix #445

- A lot of simple renamings. 
  - `AST` -> `LQP`
  - `AbstractASTNode` -> `AbstractLogicalQueryPlanNode`
  - ...
- Also renamed `SQLToASTTranslator` to `SQLTranslator` (we might want to include SQL parsing in it as well!) and `ASTToOperatorTranslator` to `LQPTranslator`. Think about it! We don't call gcc a "C++ to Machine Code compiler", it's just a "C++ Compiler". So I think this makes sense.
- Went for `AbstractLogical*Query*PlanNode` instead of `AbstractLogicalPlanNode` because even during refactoring I found it confusing whether a name should actually include the "Query" bit or not. 
- Moved the logical_query_plan/ directory to the root of src/ since even though the optimizer, in whose sub dir it was previously, works on it, the optimizer doesn't own it semantically

### CODE REVIEW

**Comment by mrzzzrm** [comment]
I think its useful to get this in (and into our heads!) before the BYOD seminar starts thinking about ASTs as well.

**Comment by mrzzzrm** [comment]
Think I did my grepping with due diligence

**Comment by mrks** [comment]
Since we are already using LQP in a number of class names as well as in the comments, maybe this should be one of the few (!) abbreviations that we expect people to learn. `AbstractLogicalQueryPlanNode` is really long and `sql_translator.hpp` looks weird because of it.

**Comment by mrzzzrm** [comment]
Alright, went for `AbstractLQPNode` because this gets typed a lot. The directory is still called `logical_query_plan/` to hopefully get people on the right track what `lqp` is. We'll get used to it...

Can be merged from my PoV

**Pull request merged**
